<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1536656950406" stop="1536656950414">
  <name>test_class</name>
  <labels/>
  <test-cases>
    <test-case start="1536656950406" status="passed" stop="1536656950410">
      <name>TestClass.test_one</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="3552-MainThread"/>
        <label name="host" value="LUOPAN"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1536656950411" status="failed" stop="1536656950414">
      <name>TestClass.test_two</name>
      <failure>
        <message>AssertionError: assert False
 +  where False = hasattr('hello', 'check')</message>
        <stack-trace>self = &lt;test_class.TestClass object at 0x0000000003D45C88&gt;

    def test_two(self):
        x = "hello"
&gt;       assert hasattr(x, 'check')
E       AssertionError: assert False
E        +  where False = hasattr('hello', 'check')

test_class.py:10: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="3552-MainThread"/>
        <label name="host" value="LUOPAN"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
